[package]
name = "rust-chess"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
clap  = { version = "4.4.7", features = ["derive"] }
tikv-jemallocator = "0.5.4"

[[bin]]         
name = "perft"